#!/bin/python3

import math
import os
import random
import re
import sys
import itertools

#
# Complete the 'arrayManipulation' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def arrayManipulation(n, queries):
    lst = [0]*(n+1)
    # Write your code here
    for a,b,k in queries:
        lst[a-1] += k
        # if b < n:
        lst[b] -= k
    ans = 0  
    prefix = itertools.accumulate(lst)
    for i in prefix:
        ans = max(i,ans)
    return ans

# arrayManipulation(5,[[1,2,100],[2,5,100],[3,4,100]])


        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
